handlers:
  - sink: sys.stderr
    level: "INFO"
    format: '[{time}] {message}'
  - sink: debug.log
    level: "DEBUG"
    enqueue: true
    serialize: false
    rotation: "1 hour"
    compression: "gz"
