handlers:
  - sink: sys.stderr
    level: "INFO"
    # format: "[{time}] {message}"
  - sink: debug.log
    level: "INFO"
    enqueue: true
    serialize: false
    rotation: "1 hour"
    compression: "gz"
